### ISSUE TITLE
Cannot paste connection URI in new connection input box

### ISSUE THREAD

**Issue by anishkny** [mongodb-js/vscode#316] opened 2021-07-15 04:10 UTC
## Bug Report

Cannot paste connection URI in new connection input box. The contents of clipboard are a MongoDB Atlas URI of the format `mongodb+srv://***:***@***.mongodb.net/dev?retryWrites=true&w=majority`

#### Environment

- node.js / npm versions: v14.15.1, 6.14.8
- OS: Mac OS Catalina 10.15.6

**Comment by Anemy** [comment] 2021-07-15 13:58
Hi @anishkny - thanks for opening the issue.
I think this might be an issue with another extension in vscode capturing key actions so that vscode can't properly handle them. 

Here's what my shortcuts for command+v look like (preferences->Keyboard shortcuts):
<img width="1158" alt="Screen Shot 2021-07-13 at 12 39 24 PM" src="https://user-images.githubusercontent.com/1791149/125499800-28a0ca85-baa9-4cfc-bc54-a3f8380a2205.png">

Are there more shortcuts registered in your vscode for pasting? Do you have other extensions installed? Which extensions?

Duplicate of https://github.com/mongodb-js/vscode/issues/310 - going to leave this open so hopefully we can get to the bottom of it.

**Comment by anishkny** [comment] 2021-07-15 15:15
Hi @Anemy thanks for getting back. I should say this is an **excellent** extension and what I am facing is a minor issue.

Here are my keybindings for `cmd+v`, I don't really see anything sus? Would be glad to help out with any other debugging steps lmk.

<img width="1552" alt="Screen Shot 2021-07-15 at 8 13 47 AM" src="https://user-images.githubusercontent.com/357499/125812278-8f4f96e4-bd2f-4133-b637-09226a301771.png">

**Comment by Anemy** [comment] 2021-07-15 15:27
@anishkny hmmm thanks... We're looking into this. Just was able to replicate. As a work around you can right click -> paste

**Comment by Anemy** [comment] 2021-07-15 15:38
Looks like a vscode bug: https://github.com/microsoft/vscode/issues/127881
Going to leave this issue open until that one is resolved in case more people run into it. Thanks again for bringing it up!

**Comment by Anemy** [comment] 2021-08-16 10:17
Fixed in https://github.com/microsoft/vscode/commit/f882d49bc7b72b8417f0aba686ed6d76960d5de7
Verified it's working as expected now with connecting. Closing :) Thanks again for reporting @anishkny and @Marveloos3WebD2

**Closed by Anemy** 2021-08-16 10:17 UTC
Labels: blocked
