### ISSUE TITLE
Mongo Shell launch error

### ISSUE THREAD

**Issue by rafee** [mongodb-js/vscode#101] opened 2020-05-15 22:12 UTC
I get the following error when I try to connect to launch the shell.

`FailedToParse: Database name cannot have reserved characters for mongodb:// URL: mongodb+srv://admin:`

Environment Details:
VSCode: 1.45.1
OS: WSL Ubuntu 20.04
Mongo Shell: 3.6.8

**Comment by alenakhineika** [comment] 2020-05-25 10:23
Try to change your default Shell in VSCode. Run the `Terminal: Select Default Shell` from the command palette and select Windows PowerShell. Note that you should reopen the terminal to apply the configuration.

We have a ticket for opening mongodb shell gracefully on all environments, we will check if we can preselect PowerShell automatically for Windows/WSL environments.

**Comment by rafee** [comment] 2020-05-28 00:23
Does that mean mongo shell doesn't work with WSL?

**Comment by Anemy** [comment] 2020-06-17 12:36
@rafee version `0.0.4` is live with a fix for mongo shell in various environments. We'll close this issue, but please feel free to reopen if you find the issue is still happening.

Thanks!

**Closed by Anemy** 2020-06-17 12:36 UTC
Labels: 0.0.4
