### ISSUE TITLE
not authorized on admin to execute command { listDatabases: 1 ... }

### ISSUE THREAD

**Issue by mcortecchia** [mongodb-js/vscode#96] opened 2020-05-15 13:48 UTC
Would it be possible to manually input the database name, instead of listing ?

**Comment by simonaberry** [comment] 2020-05-16 13:20
hitting the same issue .... even if you add the database name to your connection string, it gets ignored.

**Comment by jesperordrup** [comment] 2021-02-16 14:02
Also running on into this problem.

Using connectstring with database specified results in connection error.

Using dialog doesn't allow for specifying database (only Auth dB) and connecting fails.

Suggested solution: Allow for specifying dB

**Comment by whyname** [comment] 2021-06-01 06:43
Is the problem not going to be fixed?

**Comment by mogarick** [comment] 2021-07-14 05:45
I'm hitting this same problem. 
Even though the conn string has the DB name indicated, when trying to expand the connection tree, it always tries to list the `admin` db and that is only possible if the user has a privileged role such as `dbAdminAnyDatabase@admin`.

I made a dive into the code and found this method on `src/language/worker.ts`:

``` js
const getListDatabases = async (
  connectionString: string,
  connectionOptions: any
) => {
  try {
    const serviceProvider: CliServiceProvider = await CliServiceProvider.connect(
      connectionString,
      connectionOptions
    );

    // TODO: There is a mistake in the service provider interface
    // Use `admin` as arguments to get list of dbs
    // and remove it later when `mongosh` will merge a fix
    const result = await serviceProvider.listDatabases('admin');
    const databases = result
      ? result.databases.map((item) => ({
        label: item.name,
        kind: CompletionItemKind.Value
      }))
      : [];

    return [null, databases];
  } catch (error) {
    return [error];
  }
};
```
the `TODO` added by @alenakhineika documents the need to add `admin` as argument due to `mongosh` problem. 
Sadly the comment doesn't include a link to such bug so at the moment is not possible to know if it's still open or if it was fixed and the workaround can be removed.

Meanwhile it appears listing the `admin` db is gonna be needed and a user connecting from vscode needs the corresponding privilege to list the `admin` DB.

**Comment by mcasimir** [comment] 2021-07-14 11:02
@mogarick If recall it right the TODO mentioned there is not a bug. @alenakhineika refers to an "ergonomic" defect in the interface of the `ServiceProvider` interface that requires to pass `admin` to `listDatabases` while that should not be necessary since you can only list databases on `admin`.

**Comment by alenakhineika** [comment] 2021-07-14 11:36
Hey, thx for bringing that up!
We are going to take a look at this problem. You can track the progress here: https://jira.mongodb.org/browse/VSCODE-157

**Comment by Anemy** [comment] 2021-07-27 14:51
@mcortecchia @whyname @mogarick @simonaberry Added support in https://github.com/mongodb-js/vscode/pull/317 and this is now live in the 0.6.8 release. Thanks for opening the issue and checking out the extension. Going to close this, feel free to reopen if it could be working better.

**Closed by Anemy** 2021-07-27 14:51 UTC
Labels: enhancement
