### ISSUE TITLE
Shell not found

### ISSUE THREAD

**Issue by delcon** [mongodb-js/vscode#99] opened 2020-05-15 17:03 UTC
I can mongo shell works in cmd and powershell, but not from VsCode in your extention.

![mongoShell](https://user-images.githubusercontent.com/9477898/82076647-75b62980-96de-11ea-92f6-351749947e65.PNG)

**Comment by Anemy** [comment] 2020-05-15 17:38
Thanks - I think the way we're setting & unsetting environment variables here isn't windows friendly as well - we've got a ticket to improve this and make it work nicer for all environments. 

I'll post here when we've got a fix in progress/PR/merged :) Thanks for bringing it up!

**Comment by Anemy** [comment] 2020-05-26 17:06
@delcon Which shell do you have as your default shell in vscode?

**Comment by delcon** [comment] 2020-05-26 17:58
I have `terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe` set as terminal  
  
Today the MongoShell is connecting, but it always connects to localhost and does not use the active connection  

![mongoShell2](https://user-images.githubusercontent.com/9477898/82934018-221fc780-9f8b-11ea-8206-a34788cea15e.png)

**Comment by Anemy** [comment] 2020-06-17 12:45
@rafee version 0.0.4 is live with a fix for mongo shell on windows. We'll close this issue - please feel free to reopen if you find the issue is still happening.

Thanks again for reporting it.

**Closed by Anemy** 2020-06-17 12:45 UTC
Labels: 0.0.4
