### ISSUE TITLE
Error connection mongoldb to viscose ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by fadelfffar** [mongodb-js/vscode#411] opened 2022-04-30 03:34 UTC
Hi all,

OS: MacOS Monterey (12.3.1)
VSCode: 1.66.2
MongoDB Extension: 0.9.2

I just had some issue connecting to a MongoDB server running inside Visual Code

I kept getting the following error: Unable to connect: getaddrinfo ECONNREFUSED 127.0.0.1:27017 mongoldb and i can't seem to figure out the solution for it
![Screen Shot 2022-04-30 at 10 32 05](https://user-images.githubusercontent.com/58397488/166088966-084b8dd3-2195-404a-a25b-1d182856189a.png)

**Comment by Anemy** [comment] 2022-05-03 15:51
Hi @fadelfffar - could you tell us a little more about your MongoDB instance you are trying to connect to? Is it running on your machine on the port 27017? Is it bound to `localhost` or `127.0.0.1`?

Are you able to connect to the same instance using the [MongoDB Shell](https://www.mongodb.com/try/download/shell) `mongosh`?

**Comment by sadokmtir** [comment] 2022-05-23 11:46
@Anemy I am also having the sam problem. I could connect with robo 3T. I have a Mongo server running in a docker compose:
```
  mongo:
    image: mongo:4.2.19-bionic
    command: ["--replSet", "rs0"]
    restart: unless-stopped
    volumes:
      - mongo-configdb:/data/configdb
      - mongo-db:/data/db
    ports:
      - 27017:27017

```

**Comment by Anemy** [comment] 2022-05-23 12:58
Possible duplicate of https://github.com/mongodb-js/vscode/issues/408

**Comment by SethFalco** [comment] 2022-05-31 08:02
I run the following:
```sh
docker run -it -p 27017:27017 mongo
```

![image](https://user-images.githubusercontent.com/22801583/171123340-4fa70a91-7ea9-4ac6-8f33-5be33efdd34b.png)

I can confirm all the following work:
* `mongodb://0.0.0.0:27017/?readPreference=primary&ssl=false`
* `mongodb://127.0.0.1:27017/?readPreference=primary&ssl=false`
* `mongodb://localhost:27017/?readPreference=primary&ssl=false`

**Comment by Anemy** [comment] 2022-11-18 13:58
Going to close this issue, feel free to reopen if there's more information. Appreciate that you looked into it Seth!
Thanks for checking out the extension and opening the issue.

**Closed by Anemy** 2022-11-18 13:58 UTC
Labels: bug
