### ISSUE TITLE
Running use('dbname') in playground does not switch databases

### ISSUE THREAD

**Issue by rkiesler1** [mongodb-js/vscode#200] opened 2020-11-09 21:46 UTC
#### Current Behavior

Connected to an M0 Atlas cluster, which has a database named `acme` and an empty collection named `products`. In my playground, I run the command `use('acme');` and see the output `switched to db acme`. Next. I issue the command

```js
db.products.insertOne({ "sku": "123456789", "name": "Acme Giant Rubber Band", "qty": 120});
``` 

I see the output:

```json
{
  acknowledged: 1,
  insertedId: ObjectId("5fa9b6b4694de57a74a932a4")
}
```

However, the document is actually written to a new `products` collection in the `test` database instead of `acme`. Evaluating `db` in the playground returns `test`

#### Environment

- OS: OSX 10.15.7
- VS Code version: 1.51.0
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- NPM:  v6.14.8
- V8: 8.3.110.13-electron.0
- OS: Darwin x64 19.6.0

**Comment by Anemy** [comment] 2020-11-10 05:15
Hi @rkiesler1 - Thanks for the report. I think this works as intended. Currently a playground does not persist state between runs, think of it as a single script execution. If a database is selected in a previous playground run, the next playground execution has no knowledge of that previous execution as is set to the `test` db if no database is selected.
Does running both commands in one script produce the expected results?
```js
use('acme');

db.products.insertOne({ "sku": "123456789", "name": "Acme Giant Rubber Band", "qty": 120});
```

Going to close this for now, feel free to reopen if you'd like to make this a feature request or I'm misunderstanding the issue.

**Closed by Anemy** 2020-11-10 05:15 UTC
