### ISSUE TITLE
Request EXECUTE_ALL_FROM_PLAYGROUND failed with message: The "path" argument must be of type string

### ISSUE THREAD

**Issue by mkolinichenko** [mongodb-js/vscode#94] opened 2020-05-15 08:07 UTC
Hi! 

Thanks for this extension, looks promising, but currently I'm unable to run any playground script with the following error:

```
2020-05-15T07:55:29.682Z telemetry INFO  TELEMETRY track [
  {
    eventType: 'Command Run',
    segmentUserID: 'af1c149a-72be-4960-878c-8354014291c2',
    properties: { command: 'mdb.runAllPlaygroundBlocks' }
  }
]

2020-05-15T07:55:30.949Z playground controller ERROR Evaluate playground with cancel modal error [
  [i [Error]: Request EXECUTE_ALL_FROM_PLAYGROUND failed with message: The "path" argument must be of type string. Received type undefined
  	at /home/mk/.vscode-server/extensions/mongodb.mongodb-vscode-0.0.2/dist/extension.js:9:259621
  	at /home/mk/.vscode-server/extensions/mongodb.mongodb-vscode-0.0.2/dist/extension.js:9:259915
  	at Immediate.<anonymous> (/home/mk/.vscode-server/extensions/mongodb.mongodb-vscode-0.0.2/dist/extension.js:9:260276)
  	at processImmediate (internal/timers.js:439:21)] {
    code: -32603,
    data: undefined
  }
]
```

**Comment by mmarcon** [comment] 2020-05-15 12:44
@mkolinichenko are you running a normal VS Code installation or some remote version of it? The path `/home/mk/.vscode-server` looks unusual.

**Comment by mkolinichenko** [comment] 2020-05-15 16:38
Yep, it's [Remote WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl), sorry for not mentioning it.

**Comment by mmarcon** [comment] 2020-05-18 07:38
Cool. We'll look into that, thank you for reporting the problem.

**Comment by Anemy** [comment] 2020-06-02 16:34
Just an update, we're working on this now. We can reproduce, it looks like remote WSL has an older version of worker_threads which has a slightly different interface. Looking into a fix now.

**Comment by Anemy** [comment] 2020-06-09 08:25
Fix https://github.com/mongodb-js/vscode/pull/132 - Will be in the `0.0.4` release in the next week or so.

**Comment by Anemy** [comment] 2020-06-17 12:34
@mkolinichenko `0.0.4` is live with a fix for playgrounds in WSL :) closing this issue, feel free to reopen if you find the issue is still happening.

**Closed by Anemy** 2020-06-17 12:34 UTC
Labels: 0.0.4
