### ISSUE TITLE
Bug Report - VSCode not showing MongoDB in activity bar and side bar

### ISSUE THREAD

**Issue by diberry** [mongodb-js/vscode#412] opened 2022-05-02 17:19 UTC
#### Current Behavior

On Windows 10, VS Code dev container (Node.js + Mongo) started and the Command Palette shows MongoDB commands are available, but the green leaf icon isn't available in the activity bar and so I can't open the MongDB side bar. 

When I review the Output window items, I can see the mongdb and MongoDB Language Server are in the list. 

#### Expected Behavior/Code

Can see the green leaf icon in activity bar in order to get to side bar and interact with MongoDB playground files. 

#### Environment

- node.js / npm versions: 

outside container versions:

{
  npm: '6.14.13',
  ares: '1.17.1',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.1',
  openssl: '1.1.1k',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.67',
  zlib: '1.2.11'
}

inside container versions

{
  'msdocs-javascript-nodejs-server': '0.0.1',
  npm: '8.5.0',
  node: '16.14.2',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1n+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

- OS: Windows 10 Enterprise: 10.0.19044 Build 19044

#### Possible Solution

I've stopped and started the computer and visual studio code and neither work. The extension is installed on the local computer's version of vs code and within the container via the .devcontainer file. 

#### Additional Context/Screenshots

![image](https://user-images.githubusercontent.com/41597107/166293936-b22a3ee1-5b2b-4fc9-8206-3a083f53b3bb.png)
![image](https://user-images.githubusercontent.com/41597107/166294007-7b1fcb9d-3098-4d30-94bf-f31970d4a370.png)
![image](https://user-images.githubusercontent.com/41597107/166294085-0080370f-0d8a-411c-9d7c-645a8c6328f4.png)

**Comment by alenakhineika** [comment] 2022-05-23 09:49
Hey, thank you for reporting this! Which version of VSCode do you use? Could you pls try with the recent version of it, or any other version, or maybe with [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/)?

**Comment by SethFalco** [comment] 2022-05-28 06:28
> the green leaf icon

I'm relatively new to this extension, so I can't say I know what this is referring to.

I'm aware that the extension contributes a status bar to Visual Studio Code which is used to tell the user if actions being performed in the background. i.e. connecting or disconnecting from a database, or saving and fetching documents.

I don't see anything that resembles a static green logo to open the view, however. 🤔

As a work around though, have you tried opening the view from the Command Pallet? This should at least allow you to open the sidebar until the status menu thing is cleared up.

> \> MongoDB: Focus on Connections View

**Comment by diberry** [comment] 2022-05-31 15:36
Notice in image below the extension is installed and enabled but the mongoDB icon isn't in the far-right menu with the other controls.

@alenakhineika

- Windows 10 
- VSCode: April 2022 (version 1.67)
- MongoDB for VS Code: v0.9.3

@SethFalco Thank you for that suggestion, as you can see in the image, that command pallet command isn't available. Other ideas? 

![image](https://user-images.githubusercontent.com/41597107/171212494-bf672159-38ae-46d6-aa21-e4797615a86c.png)

**Comment by SethFalco** [comment] 2022-06-03 10:07
Can you please check the value of the `config.mdb.showMongoDBConnectionExplorer` setting?

I just checked the extension, it looks like the view/commands might not be visible when that's disabled.

If it's false, please try setting it to true.

**Comment by SethFalco** [comment] 2022-06-03 23:47
Either:
* File → Preferences → Settings (Menu navigation via mouse.)
* `ALT` + `F`, `P`, `S` (Menu navigation via keyboard.)
* `CTRL` + `,` (Shortcut to access settings.)

**Comment by diberry** [comment] 2022-06-06 15:32
![image](https://user-images.githubusercontent.com/41597107/172193712-b7451df3-1b35-480e-ab14-b0176c0c41fe.png)

**Comment by alenakhineika** [comment] 2022-06-13 09:55
I have two ideas to check.

1) Right-click on one of the visible icons on the sidebar/activity bar. If MongoDB is unchecked, recheck it and the icon should appear.

<img width="529" alt="Screenshot 2022-06-13 at 11 49 03" src="https://user-images.githubusercontent.com/16307679/173328254-713e044f-087a-46c6-9eb2-fa6a5b9271b8.png">

2) In general in VSCode, if you have moved views around and get messed up, try to run the `View: Reset View Locations` command from the command palette. Maybe it also can help with missing icons.

<img width="1166" alt="Screenshot 2022-06-13 at 11 52 16" src="https://user-images.githubusercontent.com/16307679/173328275-3d46894d-2a81-43c1-9432-ca2d568bbccb.png">

**Comment by alenakhineika** [comment] 2022-12-08 11:40
Closing the ticket. Feel free to reopen if you encounter the issue again!

**Closed by alenakhineika** 2022-12-08 11:40 UTC

**Comment by MehfoozurRehman** [comment] 2023-09-27 09:39
hey i am having same issue but i have tried the above solutions but no luch

**Comment by alenakhineika** [comment] 2023-09-28 14:32
Hey @MehfoozurRehman, could you please share the OS, VSCode, and MongoDB extension version you are using? Do you have other extensions installed that properly display icons? Could you share some screenshots of your sidebar to see how this looks for you?

**Comment by MehfoozurRehman** [comment] 2023-09-28 19:33
yes so i am running
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.25951
Mongodb extension: 1.2.1
![image](https://github.com/mongodb-js/vscode/assets/68416499/21c69cc3-c00a-47a7-848e-2990f956c49c)
i have other extension that are showing in sidebar
{
  "workbench.startupEditor": "none",
  "editor.guides.bracketPairs": true,
  "editor.inlineSuggest.enabled": true,
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorTheme": "One Dark Pro Darker",
  "liveServer.settings.donotShowInfoMsg": true,
  "editor.bracketPairColorization.enabled": true,
  "terminal.integrated.defaultProfile.windows": "Command Prompt",
  "editor.bracketPairColorization.independentColorPoolPerBracketType": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "github.copilot.enable": {
    "*": true,
    "plaintext": false,
    "markdown": true,
    "scminput": false,
    "yaml": false,
    "javascriptreact": true
  },
  "files.associations": {
    "*.js": "javascriptreact"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "git.enableSmartCommit": true,
  "editor.formatOnSave": true
}
these are my vscode settings
the extension was running on my pc for a few weeks before that then one day i needed it and i noticed no icon i tried vscode command pallet to connect to a mongodb atlas database it says connected in notification but no icon still 
i hope these details can help and thanks in advance for helping

**Comment by alenakhineika** [comment] 2023-09-28 20:06
Was trying to reproduce, but no luck so far. Could you please try downloading [VSCode Insiders](https://code.visualstudio.com/insiders/) and installing the MongoDB extension there?

I am trying to understand if this is something about a particular version of VSCode, or this happens for other VSCode builds as well.

**Comment by MehfoozurRehman** [comment] 2023-09-28 20:22
ok

**Comment by MehfoozurRehman** [comment] 2023-09-28 20:43
oh ok i found it. it was in a different panel may be i dragged it accidently into explorer panel thats why it was not showing in the side bar anyways thanks for help i dragged it outside now so its fine

**Comment by alenakhineika** [comment] 2023-09-28 21:02
Glad that you've solved the issue 🎊 Feel free to reach out in the future if any troubles!
