### ISSUE TITLE
Not launching expected MongoDB Shell

### ISSUE THREAD

**Issue by NikolajDL** [mongodb-js/vscode#142] opened 2020-07-08 10:14 UTC
#### Current Behavior

I've added a MongoDB connection to my list of connections (to a MongoDB Atlas cluster). When I right-click on this connection and select the "Launch MongoDB Shell" it opens a shell to my local MongoDB instance instead of the listed connection. 

#### Expected Behavior/Code

When I right-click on a connection and select "Launch MongoDB Shell", I expect it to open a shell to that database.

#### Environment

- node.js / npm versions: node v12.14.0 / npm 6.14.5
- OS: Windows 10
- Extension version: v0.0.4

**Comment by Anemy** [comment] 2020-07-08 13:51
Ah thanks for reporting looks like this is a bug on windows when using `powershell` as the default shell. As a temporary workaround you can set the default shell to `cmd`. https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration We'll get this into the next release - PR coming soon.

**Comment by NikolajDL** [comment] 2020-07-08 14:20
Ah, thank you, sounds good. Looking forward to the next release. Until then, I'll just "settle" with the playground. :-)

**Comment by Anemy** [comment] 2020-07-16 08:37
@NikolajDL 0.1.0 is live with a fix for launching the mongo shell with power shell :) closing this issue, feel free to reopen if you find the issue is still happening.

Thanks again for bringing it up!

**Closed by Anemy** 2020-07-16 08:37 UTC
Labels: bug
